// <auto-generated />
namespace MajeBug.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Add_BirthDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Add_BirthDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201802081752376_User_Add_BirthDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
